### ISSUE TITLE
pls support wsl

### ISSUE THREAD

**Issue by innerlee** [Maples7/vscode-terminal-inplace#1]
![image](https://user-images.githubusercontent.com/9464825/42561593-16c1452e-852c-11e8-8c14-701660f604f3.png)

**Comment by Maples7** [comment]
Got it!

I'll fix it today.

**Comment by Maples7** [comment]
I've published a new version [v1.2.0](https://github.com/Maples7/vscode-terminal-inplace/releases/tag/v1.2.0), please upgrade your extension to this version and see if it works. 😺

**Comment by innerlee** [comment]
v1.2 not fixing the problem yet.

**Comment by innerlee** [comment]
ref https://github.com/Tyriar/vscode-terminal-here/issues/15

**Comment by Maples7** [comment]
Oh my god.... It seems not so easy to fix this. But em.. I am considering using another way to achieve the same function by passing dir path to param `cwd` of VSCode developing API `vscode.window.createTerminal()`. 

I'll try this, but I can't test whether it works for your WSL terminal in my Mac. Could you help me test it by running DEBUG in your OS after I commit my changes?

**Comment by Maples7** [comment]
@innerlee LOL!!!! I'm totally thinking the same thing with you!!! 🤝 

I used the `cwd` param in my first version but It sometimes throws an exception when the path does not exists (so I add `if (fs.existsSync(focusDirPath))` statement) and I can't catch the exception in my extension (I guess VSCode does it inside).

This seems good and I'll release a new version after I add some warning message for users when the path does not exists.
